### ISSUE TITLE
Cannot deploy - "gulp-gh-pages" depends on broken version of "gift"

### ISSUE THREAD

**Issue by undfined** [allenai/oasp-website#35]
gift parses commit messages and for whatever reason breaks on PGP signed commits :( 

`/Users/tylerm/code/oasp-website/node_modules/gift/lib/commit.js:145
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
                                                       ^
TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/Users/tylerm/code/oasp-website/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/Users/tylerm/code/oasp-website/node_modules/gift/lib/commit.js:111:21)
    at /Users/tylerm/code/oasp-website/node_modules/gift/lib/commit.js:71:39
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)`

**Comment by akozyreva** [comment]
Have the same problem

**Comment by srobledo** [comment]
uugh! me too this was reported on https://github.com/shinnn/gulp-gh-pages/issues/124 but its available anymore :( it had to do with updating Gift.js
